### PR TITLE
Add zsh, remove pause at the end

### LINKED ISSUE #2: Remove pause
As mentioned by @radaken , we don't need the `pause` in the end of generated script

### PR DESCRIPTION
**Pull request by samoylenko**
Add `zsh` which I learned from @aseix about. Great alternative to `bash` and everything around it

Closes #2 as well

### CODE REVIEW

**Review by Fastex26rus — APPROVED** [review]

**Comment by radaken** [comment]
So, why is zsh better than widely used bash briefly?

**Comment by samoylenko** [comment]
> So, why is zsh better than widely used bash briefly?

It's better to google: https://www.google.com/search?q=zsh+vs+bash

zsh is a modern shell with plugins and support for git and other popular development tools. Much more advanced line completion and other nice features. There's a popular preset for it called [oh-my-zsh](https://ohmyz.sh) - you can look at their website to see what it does

My only concern was that zsh is not installed by default at most systems. Well guess what - bash too :) Both require explicit installation if needed.

**Comment by samoylenko** [comment]
This may be a good presentation to explain zsh: https://www.slideshare.net/jaguardesignstudio/why-zsh-is-cooler-than-your-shell-16194692

**Comment by samoylenko** [comment]
@radaken waiting for your approval to ensure your questions were answered. No rush, just FYI

**Review by radaken — APPROVED** [review]

**Pull request merged**
